# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/vinicius/git_workspace/missinglinkgraphic

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/vinicius/git_workspace/missinglinkgraphic

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vinicius/git_workspace/missinglinkgraphic/CMakeFiles /home/vinicius/git_workspace/missinglinkgraphic/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vinicius/git_workspace/missinglinkgraphic/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named play

# Build rule for target.
play: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 play
.PHONY : play

# fast build rule for target.
play/fast:
	$(MAKE) -f CMakeFiles/play.dir/build.make CMakeFiles/play.dir/build
.PHONY : play/fast

srcs/Objetos.o: srcs/Objetos.cpp.o

.PHONY : srcs/Objetos.o

# target to build an object file
srcs/Objetos.cpp.o:
	$(MAKE) -f CMakeFiles/play.dir/build.make CMakeFiles/play.dir/srcs/Objetos.cpp.o
.PHONY : srcs/Objetos.cpp.o

srcs/Objetos.i: srcs/Objetos.cpp.i

.PHONY : srcs/Objetos.i

# target to preprocess a source file
srcs/Objetos.cpp.i:
	$(MAKE) -f CMakeFiles/play.dir/build.make CMakeFiles/play.dir/srcs/Objetos.cpp.i
.PHONY : srcs/Objetos.cpp.i

srcs/Objetos.s: srcs/Objetos.cpp.s

.PHONY : srcs/Objetos.s

# target to generate assembly for a file
srcs/Objetos.cpp.s:
	$(MAKE) -f CMakeFiles/play.dir/build.make CMakeFiles/play.dir/srcs/Objetos.cpp.s
.PHONY : srcs/Objetos.cpp.s

srcs/main.o: srcs/main.cpp.o

.PHONY : srcs/main.o

# target to build an object file
srcs/main.cpp.o:
	$(MAKE) -f CMakeFiles/play.dir/build.make CMakeFiles/play.dir/srcs/main.cpp.o
.PHONY : srcs/main.cpp.o

srcs/main.i: srcs/main.cpp.i

.PHONY : srcs/main.i

# target to preprocess a source file
srcs/main.cpp.i:
	$(MAKE) -f CMakeFiles/play.dir/build.make CMakeFiles/play.dir/srcs/main.cpp.i
.PHONY : srcs/main.cpp.i

srcs/main.s: srcs/main.cpp.s

.PHONY : srcs/main.s

# target to generate assembly for a file
srcs/main.cpp.s:
	$(MAKE) -f CMakeFiles/play.dir/build.make CMakeFiles/play.dir/srcs/main.cpp.s
.PHONY : srcs/main.cpp.s

srcs/tinyxml2.o: srcs/tinyxml2.cpp.o

.PHONY : srcs/tinyxml2.o

# target to build an object file
srcs/tinyxml2.cpp.o:
	$(MAKE) -f CMakeFiles/play.dir/build.make CMakeFiles/play.dir/srcs/tinyxml2.cpp.o
.PHONY : srcs/tinyxml2.cpp.o

srcs/tinyxml2.i: srcs/tinyxml2.cpp.i

.PHONY : srcs/tinyxml2.i

# target to preprocess a source file
srcs/tinyxml2.cpp.i:
	$(MAKE) -f CMakeFiles/play.dir/build.make CMakeFiles/play.dir/srcs/tinyxml2.cpp.i
.PHONY : srcs/tinyxml2.cpp.i

srcs/tinyxml2.s: srcs/tinyxml2.cpp.s

.PHONY : srcs/tinyxml2.s

# target to generate assembly for a file
srcs/tinyxml2.cpp.s:
	$(MAKE) -f CMakeFiles/play.dir/build.make CMakeFiles/play.dir/srcs/tinyxml2.cpp.s
.PHONY : srcs/tinyxml2.cpp.s

srcs/xmlParser.o: srcs/xmlParser.cpp.o

.PHONY : srcs/xmlParser.o

# target to build an object file
srcs/xmlParser.cpp.o:
	$(MAKE) -f CMakeFiles/play.dir/build.make CMakeFiles/play.dir/srcs/xmlParser.cpp.o
.PHONY : srcs/xmlParser.cpp.o

srcs/xmlParser.i: srcs/xmlParser.cpp.i

.PHONY : srcs/xmlParser.i

# target to preprocess a source file
srcs/xmlParser.cpp.i:
	$(MAKE) -f CMakeFiles/play.dir/build.make CMakeFiles/play.dir/srcs/xmlParser.cpp.i
.PHONY : srcs/xmlParser.cpp.i

srcs/xmlParser.s: srcs/xmlParser.cpp.s

.PHONY : srcs/xmlParser.s

# target to generate assembly for a file
srcs/xmlParser.cpp.s:
	$(MAKE) -f CMakeFiles/play.dir/build.make CMakeFiles/play.dir/srcs/xmlParser.cpp.s
.PHONY : srcs/xmlParser.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... play"
	@echo "... edit_cache"
	@echo "... srcs/Objetos.o"
	@echo "... srcs/Objetos.i"
	@echo "... srcs/Objetos.s"
	@echo "... srcs/main.o"
	@echo "... srcs/main.i"
	@echo "... srcs/main.s"
	@echo "... srcs/tinyxml2.o"
	@echo "... srcs/tinyxml2.i"
	@echo "... srcs/tinyxml2.s"
	@echo "... srcs/xmlParser.o"
	@echo "... srcs/xmlParser.i"
	@echo "... srcs/xmlParser.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

